name: Workflow Commands(debug3)
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon"
      - name: Setting a debug message with params  
        run: echo "::debug::Missing Semicolon"
      - name: Setting an warning message with params
        run: echo "::warning::Missing Semicolon"
      - name: Setting an notice message with params
        run: echo "::notice::Missing Semicolon"