name: first-workflow
on: [push]
jobs:
  shell-cmd-job: 
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello World"  
      - name: multiple line cmd
        run: |
          node -v
          npm -v
  parallel-job:
    runs-on: macos-latest
    steps:
      - name: show software version
        run: sw_vers