name: Deploy Simple-Web to AWS EC2 using AWS CLI
on:
  push:
    branches:
      - main
jobs:
  deploys:
    runs-on: ubuntu-latest
    steps:
      - name: 1.소스코드 가져오기
        uses: actions/checkout@v3
      - name: 2.AWS 접속정보 설정
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2