## ec2 s3 deploy12
name: Deploy to AWS
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1.소스코드 다운로드 (simple-web)
        uses: actions/checkout@v2

      - name: 2.AWS CLI 접속정보 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: 3.아티팩트 만들기
        run: |
          pwd
          zip -r deploy.zip ./*

      - name: 4.S3 아티팩트 업로드
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.AWS_BUCKET }}/deploy.zip